// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: muxer.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WifiState_Interface_Type int32

const (
	WifiState_Interface_UNKNOWN  WifiState_Interface_Type = 0
	WifiState_Interface_WIFI     WifiState_Interface_Type = 1
	WifiState_Interface_ETHERNET WifiState_Interface_Type = 2
	WifiState_Interface_AP       WifiState_Interface_Type = 3
)

// Enum value maps for WifiState_Interface_Type.
var (
	WifiState_Interface_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "WIFI",
		2: "ETHERNET",
		3: "AP",
	}
	WifiState_Interface_Type_value = map[string]int32{
		"UNKNOWN":  0,
		"WIFI":     1,
		"ETHERNET": 2,
		"AP":       3,
	}
)

func (x WifiState_Interface_Type) Enum() *WifiState_Interface_Type {
	p := new(WifiState_Interface_Type)
	*p = x
	return p
}

func (x WifiState_Interface_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WifiState_Interface_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_muxer_proto_enumTypes[0].Descriptor()
}

func (WifiState_Interface_Type) Type() protoreflect.EnumType {
	return &file_muxer_proto_enumTypes[0]
}

func (x WifiState_Interface_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WifiState_Interface_Type.Descriptor instead.
func (WifiState_Interface_Type) EnumDescriptor() ([]byte, []int) {
	return file_muxer_proto_rawDescGZIP(), []int{2, 1, 0}
}

type WifiConnectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InterfaceId string `protobuf:"bytes,1,opt,name=interface_id,json=interfaceId,proto3" json:"interface_id,omitempty"`
	Bssid       string `protobuf:"bytes,2,opt,name=bssid,proto3" json:"bssid,omitempty"`
	Password    string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	// if set, the wifi will broadcast this SSID as an access point. BSSID will be ignored.
	ApModeSsid  string `protobuf:"bytes,4,opt,name=ap_mode_ssid,json=apModeSsid,proto3" json:"ap_mode_ssid,omitempty"`
	Autoconnect bool   `protobuf:"varint,5,opt,name=autoconnect,proto3" json:"autoconnect,omitempty"`
}

func (x *WifiConnectRequest) Reset() {
	*x = WifiConnectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_muxer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WifiConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WifiConnectRequest) ProtoMessage() {}

func (x *WifiConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_muxer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WifiConnectRequest.ProtoReflect.Descriptor instead.
func (*WifiConnectRequest) Descriptor() ([]byte, []int) {
	return file_muxer_proto_rawDescGZIP(), []int{0}
}

func (x *WifiConnectRequest) GetInterfaceId() string {
	if x != nil {
		return x.InterfaceId
	}
	return ""
}

func (x *WifiConnectRequest) GetBssid() string {
	if x != nil {
		return x.Bssid
	}
	return ""
}

func (x *WifiConnectRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *WifiConnectRequest) GetApModeSsid() string {
	if x != nil {
		return x.ApModeSsid
	}
	return ""
}

func (x *WifiConnectRequest) GetAutoconnect() bool {
	if x != nil {
		return x.Autoconnect
	}
	return false
}

type WifiConnectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error     string     `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	WifiState *WifiState `protobuf:"bytes,2,opt,name=wifi_state,json=wifiState,proto3" json:"wifi_state,omitempty"`
}

func (x *WifiConnectResponse) Reset() {
	*x = WifiConnectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_muxer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WifiConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WifiConnectResponse) ProtoMessage() {}

func (x *WifiConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_muxer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WifiConnectResponse.ProtoReflect.Descriptor instead.
func (*WifiConnectResponse) Descriptor() ([]byte, []int) {
	return file_muxer_proto_rawDescGZIP(), []int{1}
}

func (x *WifiConnectResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *WifiConnectResponse) GetWifiState() *WifiState {
	if x != nil {
		return x.WifiState
	}
	return nil
}

type WifiState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Interfaces []*WifiState_Interface `protobuf:"bytes,1,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
}

func (x *WifiState) Reset() {
	*x = WifiState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_muxer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WifiState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WifiState) ProtoMessage() {}

func (x *WifiState) ProtoReflect() protoreflect.Message {
	mi := &file_muxer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WifiState.ProtoReflect.Descriptor instead.
func (*WifiState) Descriptor() ([]byte, []int) {
	return file_muxer_proto_rawDescGZIP(), []int{2}
}

func (x *WifiState) GetInterfaces() []*WifiState_Interface {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

type VideoInputDevice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *VideoInputDevice) Reset() {
	*x = VideoInputDevice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_muxer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoInputDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoInputDevice) ProtoMessage() {}

func (x *VideoInputDevice) ProtoReflect() protoreflect.Message {
	mi := &file_muxer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoInputDevice.ProtoReflect.Descriptor instead.
func (*VideoInputDevice) Descriptor() ([]byte, []int) {
	return file_muxer_proto_rawDescGZIP(), []int{3}
}

func (x *VideoInputDevice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VideoInputDevice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AudioInputDevice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *AudioInputDevice) Reset() {
	*x = AudioInputDevice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_muxer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AudioInputDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioInputDevice) ProtoMessage() {}

func (x *AudioInputDevice) ProtoReflect() protoreflect.Message {
	mi := &file_muxer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioInputDevice.ProtoReflect.Descriptor instead.
func (*AudioInputDevice) Descriptor() ([]byte, []int) {
	return file_muxer_proto_rawDescGZIP(), []int{4}
}

func (x *AudioInputDevice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AudioInputDevice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeviceState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoInputDevices []*VideoInputDevice `protobuf:"bytes,1,rep,name=video_input_devices,json=videoInputDevices,proto3" json:"video_input_devices,omitempty"`
	AudioInputDevices []*AudioInputDevice `protobuf:"bytes,2,rep,name=audio_input_devices,json=audioInputDevices,proto3" json:"audio_input_devices,omitempty"`
}

func (x *DeviceState) Reset() {
	*x = DeviceState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_muxer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceState) ProtoMessage() {}

func (x *DeviceState) ProtoReflect() protoreflect.Message {
	mi := &file_muxer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceState.ProtoReflect.Descriptor instead.
func (*DeviceState) Descriptor() ([]byte, []int) {
	return file_muxer_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceState) GetVideoInputDevices() []*VideoInputDevice {
	if x != nil {
		return x.VideoInputDevices
	}
	return nil
}

func (x *DeviceState) GetAudioInputDevices() []*AudioInputDevice {
	if x != nil {
		return x.AudioInputDevices
	}
	return nil
}

type WifiState_AccessPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ssid           string  `protobuf:"bytes,1,opt,name=ssid,proto3" json:"ssid,omitempty"`
	Bssid          string  `protobuf:"bytes,2,opt,name=bssid,proto3" json:"bssid,omitempty"`
	SignalStrength float64 `protobuf:"fixed64,3,opt,name=signal_strength,json=signalStrength,proto3" json:"signal_strength,omitempty"`
	Security       string  `protobuf:"bytes,4,opt,name=security,proto3" json:"security,omitempty"`
}

func (x *WifiState_AccessPoint) Reset() {
	*x = WifiState_AccessPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_muxer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WifiState_AccessPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WifiState_AccessPoint) ProtoMessage() {}

func (x *WifiState_AccessPoint) ProtoReflect() protoreflect.Message {
	mi := &file_muxer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WifiState_AccessPoint.ProtoReflect.Descriptor instead.
func (*WifiState_AccessPoint) Descriptor() ([]byte, []int) {
	return file_muxer_proto_rawDescGZIP(), []int{2, 0}
}

func (x *WifiState_AccessPoint) GetSsid() string {
	if x != nil {
		return x.Ssid
	}
	return ""
}

func (x *WifiState_AccessPoint) GetBssid() string {
	if x != nil {
		return x.Bssid
	}
	return ""
}

func (x *WifiState_AccessPoint) GetSignalStrength() float64 {
	if x != nil {
		return x.SignalStrength
	}
	return 0
}

func (x *WifiState_AccessPoint) GetSecurity() string {
	if x != nil {
		return x.Security
	}
	return ""
}

type WifiState_Interface struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type WifiState_Interface_Type `protobuf:"varint,2,opt,name=type,proto3,enum=api.WifiState_Interface_Type" json:"type,omitempty"`
	// these fields only set if type == WIFI
	ConnectedAccessPointSsid string                   `protobuf:"bytes,3,opt,name=connected_access_point_ssid,json=connectedAccessPointSsid,proto3" json:"connected_access_point_ssid,omitempty"`
	DiscoveredAccessPoints   []*WifiState_AccessPoint `protobuf:"bytes,4,rep,name=discovered_access_points,json=discoveredAccessPoints,proto3" json:"discovered_access_points,omitempty"`
	Autoconnect              bool                     `protobuf:"varint,5,opt,name=autoconnect,proto3" json:"autoconnect,omitempty"`
}

func (x *WifiState_Interface) Reset() {
	*x = WifiState_Interface{}
	if protoimpl.UnsafeEnabled {
		mi := &file_muxer_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WifiState_Interface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WifiState_Interface) ProtoMessage() {}

func (x *WifiState_Interface) ProtoReflect() protoreflect.Message {
	mi := &file_muxer_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WifiState_Interface.ProtoReflect.Descriptor instead.
func (*WifiState_Interface) Descriptor() ([]byte, []int) {
	return file_muxer_proto_rawDescGZIP(), []int{2, 1}
}

func (x *WifiState_Interface) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WifiState_Interface) GetType() WifiState_Interface_Type {
	if x != nil {
		return x.Type
	}
	return WifiState_Interface_UNKNOWN
}

func (x *WifiState_Interface) GetConnectedAccessPointSsid() string {
	if x != nil {
		return x.ConnectedAccessPointSsid
	}
	return ""
}

func (x *WifiState_Interface) GetDiscoveredAccessPoints() []*WifiState_AccessPoint {
	if x != nil {
		return x.DiscoveredAccessPoints
	}
	return nil
}

func (x *WifiState_Interface) GetAutoconnect() bool {
	if x != nil {
		return x.Autoconnect
	}
	return false
}

var File_muxer_proto protoreflect.FileDescriptor

var file_muxer_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6d, 0x75, 0x78, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61,
	0x70, 0x69, 0x22, 0xad, 0x01, 0x0a, 0x12, 0x57, 0x69, 0x66, 0x69, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x62, 0x73, 0x73, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x73, 0x73,
	0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x20,
	0x0a, 0x0c, 0x61, 0x70, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x5f, 0x73, 0x73, 0x69, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x70, 0x4d, 0x6f, 0x64, 0x65, 0x53, 0x73, 0x69, 0x64,
	0x12, 0x20, 0x0a, 0x0b, 0x61, 0x75, 0x74, 0x6f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x61, 0x75, 0x74, 0x6f, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x22, 0x5a, 0x0a, 0x13, 0x57, 0x69, 0x66, 0x69, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x2d, 0x0a, 0x0a, 0x77, 0x69, 0x66, 0x69, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x57, 0x69, 0x66, 0x69, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x09, 0x77, 0x69, 0x66, 0x69, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x80,
	0x04, 0x0a, 0x09, 0x57, 0x69, 0x66, 0x69, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x38, 0x0a, 0x0a,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x57, 0x69, 0x66, 0x69, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x1a, 0x7c, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x73, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x73, 0x73,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x73, 0x73, 0x69, 0x64, 0x12,
	0x27, 0x0a, 0x0f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x6e, 0x67,
	0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c,
	0x53, 0x74, 0x72, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x63, 0x75,
	0x72, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x63, 0x75,
	0x72, 0x69, 0x74, 0x79, 0x1a, 0xba, 0x02, 0x0a, 0x09, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x31, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x57, 0x69, 0x66, 0x69, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x3d, 0x0a, 0x1b, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f,
	0x73, 0x73, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x18, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x65, 0x64, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x53, 0x73, 0x69, 0x64, 0x12, 0x54, 0x0a, 0x18, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72,
	0x65, 0x64, 0x5f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x57, 0x69, 0x66,
	0x69, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x52, 0x16, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x65, 0x64, 0x41, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x75,
	0x74, 0x6f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0b, 0x61, 0x75, 0x74, 0x6f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x22, 0x33, 0x0a, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x57, 0x49, 0x46, 0x49, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x45,
	0x54, 0x48, 0x45, 0x52, 0x4e, 0x45, 0x54, 0x10, 0x02, 0x12, 0x06, 0x0a, 0x02, 0x41, 0x50, 0x10,
	0x03, 0x22, 0x36, 0x0a, 0x10, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x36, 0x0a, 0x10, 0x41, 0x75, 0x64,
	0x69, 0x6f, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x9b, 0x01, 0x0a, 0x0b, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x45, 0x0a, 0x13, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74,
	0x5f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x11, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x45, 0x0a, 0x13, 0x61, 0x75, 0x64, 0x69,
	0x6f, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x75, 0x64, 0x69,
	0x6f, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x11, 0x61, 0x75,
	0x64, 0x69, 0x6f, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x42,
	0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x75,
	0x78, 0x61, 0x62, 0x6c, 0x65, 0x2f, 0x72, 0x74, 0x70, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x2f, 0x61,
	0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_muxer_proto_rawDescOnce sync.Once
	file_muxer_proto_rawDescData = file_muxer_proto_rawDesc
)

func file_muxer_proto_rawDescGZIP() []byte {
	file_muxer_proto_rawDescOnce.Do(func() {
		file_muxer_proto_rawDescData = protoimpl.X.CompressGZIP(file_muxer_proto_rawDescData)
	})
	return file_muxer_proto_rawDescData
}

var file_muxer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_muxer_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_muxer_proto_goTypes = []interface{}{
	(WifiState_Interface_Type)(0), // 0: api.WifiState.Interface.Type
	(*WifiConnectRequest)(nil),    // 1: api.WifiConnectRequest
	(*WifiConnectResponse)(nil),   // 2: api.WifiConnectResponse
	(*WifiState)(nil),             // 3: api.WifiState
	(*VideoInputDevice)(nil),      // 4: api.VideoInputDevice
	(*AudioInputDevice)(nil),      // 5: api.AudioInputDevice
	(*DeviceState)(nil),           // 6: api.DeviceState
	(*WifiState_AccessPoint)(nil), // 7: api.WifiState.AccessPoint
	(*WifiState_Interface)(nil),   // 8: api.WifiState.Interface
}
var file_muxer_proto_depIdxs = []int32{
	3, // 0: api.WifiConnectResponse.wifi_state:type_name -> api.WifiState
	8, // 1: api.WifiState.interfaces:type_name -> api.WifiState.Interface
	4, // 2: api.DeviceState.video_input_devices:type_name -> api.VideoInputDevice
	5, // 3: api.DeviceState.audio_input_devices:type_name -> api.AudioInputDevice
	0, // 4: api.WifiState.Interface.type:type_name -> api.WifiState.Interface.Type
	7, // 5: api.WifiState.Interface.discovered_access_points:type_name -> api.WifiState.AccessPoint
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_muxer_proto_init() }
func file_muxer_proto_init() {
	if File_muxer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_muxer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WifiConnectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_muxer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WifiConnectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_muxer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WifiState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_muxer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoInputDevice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_muxer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AudioInputDevice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_muxer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_muxer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WifiState_AccessPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_muxer_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WifiState_Interface); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_muxer_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_muxer_proto_goTypes,
		DependencyIndexes: file_muxer_proto_depIdxs,
		EnumInfos:         file_muxer_proto_enumTypes,
		MessageInfos:      file_muxer_proto_msgTypes,
	}.Build()
	File_muxer_proto = out.File
	file_muxer_proto_rawDesc = nil
	file_muxer_proto_goTypes = nil
	file_muxer_proto_depIdxs = nil
}
